### ISSUE TITLE
WindowsError: [Error 267] The directory name is invalid: u'assignments/Programming Assignment 1: WordNet'

### ISSUE THREAD

**Issue by ymohammad** [Chillee/coursera-dl-all#8]
Got an error. It looks, program is trying to create a Directory with a name containing invalid character. Please see the below output.

```
('https://class.coursera.org/algs4partII-007/', 'algs4partII-007')
Logging In....
Logged in!
[(u'https://class.coursera.org/algs4partII-007/wiki/view?page=schedule', u'Schedule'), (u'https://class.coursera.org/algs4partII-007/wiki/ScheduleGoogleHangouts
', u'GoogleHangouts'), (u'https://class.coursera.org/algs4partII-007/class/index', u'Home'), (u'https://class.coursera.org/algs4partII-007/wiki/view?page=errata
', u'Errata'), (u'https://class.coursera.org/algs4partII-007/wiki/view?page=syllabus', u'Syllabus'), (u'https://class.coursera.org/algs4partII-007/assignment/in
dex', u'ProgrammingAssignments'), (u'https://class.coursera.org/algs4partII-007/forum/index', u'DiscussionForums')]
Downloading Quizzes....
Downloading Surveys
Downloading Job Interview Questions
Downloading Exercises
Programming Assignment 1: WordNet
Help Center
Programming Assignment 2: Seam Carving
Help Center
Programming Assignment 3: Baseball Elimination
Help Center
Programming Assignment 4: Boggle
Help Center
Programming Assignment 5: Burrows-Wheeler
Help Center
[u'Programming Assignment 1: WordNet', u'Programming Assignment 2: Seam Carving', u'Programming Assignment 3: Baseball Elimination', u'Programming Assignment 4:
 Boggle', u'Programming Assignment 5: Burrows-Wheeler']
Traceback (most recent call last):
  File "dl_all.py", line 304, in <module>
    download_all_assignments(session, assign_info)
  File "dl_all.py", line 213, in download_all_assignments
    download_all_zips_on_page(session, 'assignments/'+i[1])
  File "dl_all.py", line 99, in download_all_zips_on_page
    os.makedirs(path)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 267] The directory name is invalid: u'assignments/Programming Assignment 1: WordNet'
```

**Comment by Chillee** [comment]
Try the newest version.

I believe I've fixed this bug.

**Comment by Chillee** [comment]
This should have been fixed in some previous commit.
